- name: Install Docker on Ubuntu 24.04 (official method)
  hosts: vps
  become: yes
  vars:
    docker_gpg_dir: /etc/apt/keyrings
    docker_gpg_key: /etc/apt/keyrings/docker.asc
    docker_repo: "deb [arch=amd64 signed-by={{ docker_gpg_key }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  tasks:
    - name: Ensure required dependencies are installed
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create keyring directory
      file:
        path: "{{ docker_gpg_dir }}"
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: "{{ docker_gpg_key }}"
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user 'ubuntu' to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
